### ISSUE TITLE
Issue with divinity prefix in menus

### ISSUE THREAD

**Issue by goflishMC** [magemonkeystudio/fusion#29]
Fusion 1.0.0.1-R0.1
Codex 1.0.0-R0.18

Fusion is not reading the `DIVINITY_` prefix in config.yml menus

this is what trav said about this issue: https://i.imgur.com/HIzIXmx.png

**Comment by Sentropic** [comment]
Fixed by commits:
https://github.com/magemonkeystudio/divinity/commit/7796e6c776058d53332a8e6e2e77bde834a0202c
https://github.com/magemonkeystudio/codex/commit/2c7dc4a08f7645106c1e54f6efc9126260bdb3cd
https://github.com/magemonkeystudio/codex/commit/b3df2a54e583e253645976f275be871c1346878f
https://github.com/magemonkeystudio/fusion/commit/289f9a4b7044e3351e51c1362f39077aff6234bb
https://github.com/magemonkeystudio/fusion/commit/2c7f34076cf39d6b88ed82178a4754e75904fa53
